### ISSUE TITLE
Repository ownership management

### ISSUE THREAD

**Issue by sethrj** [sethrj/anstrans#8]
Hi @snschune @rachelslaybaugh , you both are owners of this organization, and when I transferred the ANS transactions from my personal `sethrj/` repository to here I didn't realize I wouldn't be able to manage the settings on this repo. Can you please make me and @jkulesza owners of this repo? Thanks.

**Comment by rachelslaybaugh** [comment]
I made you both admins

**Comment by sethrj** [comment]
Thanks @rachelslaybaugh !

**Comment by jkulesza** [comment]
Indeed, thanks @rachelslaybaugh!
